<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An open undergraduate textbook for Econometrics I at the University of Granada. Combines lecture notes, R tutorials, and interactive self-assessment in a single reproducible volume.">

<title>1&nbsp; Initial Concepts – Econometrics I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/02-simple-regression.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-acff971833d9769290026d534105daaa.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-initial-concepts.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Initial Concepts</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Econometrics I</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-initial-concepts.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Initial Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-simple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Simple Linear Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Multiple Linear Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Prediction and Model Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-nonlinear-qualitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Nonlinear Relationships and Qualitative Information</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-heteroskedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Heteroskedasticity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-autocorrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Autocorrelation</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-a-prerequisites.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathematical and Statistical Prerequisites</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-b-wooldridge-cgl-crosswalk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Wooldridge ↔︎ Carter–Griffiths–Lim Crosswalk</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-c-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Statistical Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  <li><a href="#motivating-empirical-question" id="toc-motivating-empirical-question" class="nav-link" data-scroll-target="#motivating-empirical-question">Motivating empirical question</a></li>
  <li><a href="#what-is-econometrics" id="toc-what-is-econometrics" class="nav-link" data-scroll-target="#what-is-econometrics"><span class="header-section-number">1.1</span> What is econometrics?</a></li>
  <li><a href="#the-econometric-model" id="toc-the-econometric-model" class="nav-link" data-scroll-target="#the-econometric-model"><span class="header-section-number">1.2</span> The econometric model</a></li>
  <li><a href="#uses-of-econometrics" id="toc-uses-of-econometrics" class="nav-link" data-scroll-target="#uses-of-econometrics"><span class="header-section-number">1.3</span> Uses of econometrics</a></li>
  <li><a href="#correlation-does-not-imply-causation" id="toc-correlation-does-not-imply-causation" class="nav-link" data-scroll-target="#correlation-does-not-imply-causation"><span class="header-section-number">1.4</span> Correlation does not imply causation</a>
  <ul class="collapse">
  <li><a href="#selection-bias" id="toc-selection-bias" class="nav-link" data-scroll-target="#selection-bias"><span class="header-section-number">1.4.1</span> Selection bias</a></li>
  <li><a href="#omitted-variable-bias" id="toc-omitted-variable-bias" class="nav-link" data-scroll-target="#omitted-variable-bias"><span class="header-section-number">1.4.2</span> Omitted variable bias</a></li>
  <li><a href="#why-randomisation-solves-the-problem" id="toc-why-randomisation-solves-the-problem" class="nav-link" data-scroll-target="#why-randomisation-solves-the-problem"><span class="header-section-number">1.4.3</span> Why randomisation solves the problem</a></li>
  </ul></li>
  <li><a href="#types-of-experiments" id="toc-types-of-experiments" class="nav-link" data-scroll-target="#types-of-experiments"><span class="header-section-number">1.5</span> Types of experiments</a>
  <ul class="collapse">
  <li><a href="#randomised-experiments" id="toc-randomised-experiments" class="nav-link" data-scroll-target="#randomised-experiments"><span class="header-section-number">1.5.1</span> Randomised experiments</a></li>
  <li><a href="#quasi-experiments" id="toc-quasi-experiments" class="nav-link" data-scroll-target="#quasi-experiments"><span class="header-section-number">1.5.2</span> Quasi-experiments</a></li>
  <li><a href="#nonexperimental-observational-data" id="toc-nonexperimental-observational-data" class="nav-link" data-scroll-target="#nonexperimental-observational-data"><span class="header-section-number">1.5.3</span> Nonexperimental (observational) data</a></li>
  </ul></li>
  <li><a href="#types-of-economic-data" id="toc-types-of-economic-data" class="nav-link" data-scroll-target="#types-of-economic-data"><span class="header-section-number">1.6</span> Types of economic data</a></li>
  <li><a href="#lab-exploring-economic-data" id="toc-lab-exploring-economic-data" class="nav-link" data-scroll-target="#lab-exploring-economic-data"><span class="header-section-number">1.7</span> Lab: exploring economic data</a>
  <ul class="collapse">
  <li><a href="#structure-size-and-a-first-look" id="toc-structure-size-and-a-first-look" class="nav-link" data-scroll-target="#structure-size-and-a-first-look"><span class="header-section-number">1.7.1</span> Structure, size, and a first look</a></li>
  <li><a href="#summary-statistics-and-distributions" id="toc-summary-statistics-and-distributions" class="nav-link" data-scroll-target="#summary-statistics-and-distributions"><span class="header-section-number">1.7.2</span> Summary statistics and distributions</a></li>
  <li><a href="#frequency-tables" id="toc-frequency-tables" class="nav-link" data-scroll-target="#frequency-tables"><span class="header-section-number">1.7.3</span> Frequency tables</a></li>
  <li><a href="#a-first-scatter-plot" id="toc-a-first-scatter-plot" class="nav-link" data-scroll-target="#a-first-scatter-plot"><span class="header-section-number">1.7.4</span> A first scatter plot</a></li>
  <li><a href="#conditional-means-a-preview-of-regression" id="toc-conditional-means-a-preview-of-regression" class="nav-link" data-scroll-target="#conditional-means-a-preview-of-regression"><span class="header-section-number">1.7.5</span> Conditional means: a preview of regression</a></li>
  </ul></li>
  <li><a href="#self-check" id="toc-self-check" class="nav-link" data-scroll-target="#self-check">Self-check</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Initial Concepts</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-outcomes" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>By the end of this chapter the reader should be able to:</p>
<ul>
<li>Explain what econometrics is and how an econometric model differs from a purely theoretical economic model.</li>
<li>Interpret the two components of an econometric model: the systematic part and the random error <span class="math inline">\(u\)</span>.</li>
<li>Distinguish correlation from causation, and identify selection bias and omitted-variable bias in concrete examples.</li>
<li>Explain why randomisation eliminates selection bias on average, and contrast randomised experiments with quasi-experimental and observational designs.</li>
<li>Classify a dataset as cross-sectional, time-series, panel, or pooled cross-section, and recognise the research questions each structure can (and cannot) answer.</li>
<li>Use basic R commands (<code>str()</code>, <code>summary()</code>, <code>head()</code>, <code>hist()</code>, <code>plot()</code>, <code>tapply()</code>, <code>cor()</code>) to explore a microeconomic dataset and compute conditional means.</li>
</ul>
</section>
<section id="motivating-empirical-question" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="motivating-empirical-question">Motivating empirical question</h2>
<blockquote class="blockquote">
<p><em>Does going to university <strong>cause</strong> higher wages, or do the people who would have earned more anyway tend to go to university?</em></p>
</blockquote>
<p>This single question drives the rest of the course. A correlation between schooling and wages is easy to compute; turning that correlation into a credible statement about the causal return to education is hard. The tools we develop — the linear model, the assumptions on the error term, randomisation, controls, and tests — are all in the service of answering questions of this form.</p>
</section>
<section id="what-is-econometrics" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="what-is-econometrics"><span class="header-section-number">1.1</span> What is econometrics?</h2>
<p> is the application of statistical methods to economic data, with the goal of giving empirical content to economic relationships <span class="citation" data-cites="wooldridge2020 cgl2017">(<a href="#ref-wooldridge2020" role="doc-biblioref">Wooldridge 2020</a>; <a href="#ref-cgl2017" role="doc-biblioref">Hill et al. 2017</a>)</span>. Its main objective is the <strong>estimation of relationships between variables</strong>. Typical pairs of interest in this course include:</p>
<ul>
<li>Education <span class="math inline">\(\Rightarrow\)</span> Salary</li>
<li>Class attendance <span class="math inline">\(\Rightarrow\)</span> Final grade</li>
<li>Tuition fees <span class="math inline">\(\Rightarrow\)</span> Enrolment</li>
<li>Income <span class="math inline">\(\Rightarrow\)</span> Happiness</li>
<li>Government spending <span class="math inline">\(\Rightarrow\)</span> Crime</li>
<li>Advertising <span class="math inline">\(\Rightarrow\)</span> Sales</li>
</ul>
<p>In general we write <span class="math inline">\(X \Rightarrow Y\)</span>, where <span class="math inline">\(X\)</span> is the <strong>independent variable</strong> (or regressor, explanatory variable) and <span class="math inline">\(Y\)</span> is the <strong>dependent variable</strong> (or response, outcome). Two questions then arise:</p>
<ol type="1">
<li>Is there an effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span>?</li>
<li>How large is that effect?</li>
</ol>
<p>These “how much” questions are everywhere. A city council wonders how much violent crime will fall if it spends an additional million euros on policing. A local business must estimate the relationship between advertising spending and sales. A university must estimate how much enrolment will drop if it raises tuition by 300 euros. None of these questions can be answered by economic theory alone — they require data, a statistical model, and the discipline of econometrics.</p>
</section>
<section id="the-econometric-model" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-econometric-model"><span class="header-section-number">1.2</span> The econometric model</h2>
<p>An econometric model has <strong>two</strong> components:</p>
<ol type="1">
<li>A <strong>systematic component</strong> — the average or systematic behaviour of many individuals, firms, or other units.</li>
<li>A <strong>random error</strong> <span class="math inline">\(u\)</span> (sometimes called the <em>disturbance</em>) — the many factors that affect <span class="math inline">\(Y\)</span> but are not included in the systematic part.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: salary determination
</div>
</div>
<div class="callout-body-container callout-body">
<p>The factors associated with an individual’s salary include age, gender, experience, and education. In general functional form:</p>
<p><span class="math display">\[
\text{Salary} = f(\text{Age},\,\text{Gender},\,\text{Experience},\,\text{Education}) + u.
\]</span></p>
<p>A linear specification is</p>
<p><span class="math display">\[
\text{Salary} = \beta_0 + \beta_1\,\text{Age} + \beta_2\,\text{Gender} + \beta_3\,\text{Experience} + \beta_4\,\text{Education} + u.
\]</span></p>
<p>The coefficients <span class="math inline">\(\beta_0, \beta_1, \dots, \beta_4\)</span> are <strong>unknown population parameters</strong> that we will estimate from data using an econometric technique (typically Ordinary Least Squares, introduced in Chapter 2).</p>
</div>
</div>
<p>The functional form is itself a hypothesis about how the variables are connected. A key challenge in any applied problem is choosing a functional form that is compatible both with economic theory and with what the data look like.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: confusing <span class="math inline">\(u\)</span> with the residual <span class="math inline">\(\hat u\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The error <span class="math inline">\(u\)</span> is a <em>population</em> object: it represents every determinant of <span class="math inline">\(Y\)</span> that is not in the model, and it is <strong>unobservable</strong>. The residual <span class="math inline">\(\hat u_i = y_i - \hat y_i\)</span> is its <em>sample</em> counterpart, obtained after estimating the model. Following Wooldridge’s notation, we keep <span class="math inline">\(u\)</span> and <span class="math inline">\(\hat u\)</span> strictly separate throughout the book.</p>
</div>
</div>
</section>
<section id="uses-of-econometrics" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="uses-of-econometrics"><span class="header-section-number">1.3</span> Uses of econometrics</h2>
<p>We use econometric models for three broad purposes:</p>
<ul>
<li><strong>Test economic theories and hypotheses.</strong> For example: does increasing the minimum wage reduce employment? Does class attendance improve grades?</li>
<li><strong>Predict economic variables.</strong> For example: forecast next quarter’s GDP growth, or tomorrow’s electricity demand.</li>
<li><strong>Estimate causal relationships.</strong> For example: does an additional year of education <em>cause</em> higher wages, or are educated workers simply different to begin with?</li>
</ul>
<p>The third use — credible causal inference from observational data — is at the heart of the so-called <strong>Credibility Revolution</strong> in empirical economics. Hypothesis testing and prediction are sometimes called “Led Zeppelin” econometrics; causal inference is the modern emphasis <span class="citation" data-cites="cgl2017">(<a href="#ref-cgl2017" role="doc-biblioref">Hill et al. 2017</a>)</span>.</p>
</section>
<section id="correlation-does-not-imply-causation" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="correlation-does-not-imply-causation"><span class="header-section-number">1.4</span> Correlation does not imply causation</h2>
<p>One of the most important lessons of the course — repeated, if necessary, on every page — is that <strong>correlation does not imply causation</strong>. The fact that two variables move together does not establish that one of them causes the other. Two reasons stand out: <em>selection bias</em> and <em>omitted variables</em>.</p>
<section id="selection-bias" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="selection-bias"><span class="header-section-number">1.4.1</span> Selection bias</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: ventilators and deaths
</div>
</div>
<div class="callout-body-container callout-body">
<p>A hospital wants to know whether ventilators save lives. A naive comparison shows that patients on ventilators die <em>more</em> often than patients not on ventilators. Should we conclude that ventilators <em>kill</em> patients?</p>
<p>Obviously not. The problem is <strong>selection bias</strong>: the sickest patients are precisely the ones who are placed on a ventilator. These patients would have had a higher mortality rate <em>regardless</em> of whether they received a ventilator.</p>
<p>The observed correlation between ventilator use and death is <em>positive</em>; the true causal effect of ventilators on survival is <em>negative</em>. A naive comparison can therefore give us not just the wrong magnitude but the <strong>wrong sign</strong> of the effect.</p>
</div>
</div>
<p>The lesson is general: whenever treatment is not assigned randomly, simple comparisons of outcomes between treated and untreated units confound the causal effect of the treatment with the characteristics of the units that selected into it.</p>
</section>
<section id="omitted-variable-bias" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="omitted-variable-bias"><span class="header-section-number">1.4.2</span> Omitted variable bias</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: ice cream and drowning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Data show a strong positive correlation between ice-cream sales and drowning deaths. Should we ban ice cream to prevent drowning?</p>
<p>Of course not. The <strong>omitted variable</strong> is <em>temperature</em>. Hot weather causes both more ice-cream sales and more swimming (hence more drowning). Without controlling for temperature, the correlation between ice cream and drowning is a <strong>spurious correlation</strong> — a real statistical association with no causal content.</p>
</div>
</div>
<p>Whenever a variable that influences <span class="math inline">\(Y\)</span> is also correlated with <span class="math inline">\(X\)</span> but is left out of the model, the estimate of the effect of <span class="math inline">\(X\)</span> will be biased. We will study this formally as <strong>omitted variable bias</strong> in Chapter 3.</p>
</section>
<section id="why-randomisation-solves-the-problem" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="why-randomisation-solves-the-problem"><span class="header-section-number">1.4.3</span> Why randomisation solves the problem</h3>
<p>If we <strong>randomly</strong> assign individuals to a treatment group and a control group, then on average the two groups will have the same observable and unobservable characteristics <em>before</em> the treatment is administered. Any difference in outcomes <em>after</em> the treatment can therefore be attributed to the treatment itself.</p>
<p>In the ventilator example, if we could randomly assign ventilators (not based on severity of illness), then the treatment and control groups would have the same average severity. The difference in mortality between the two groups would be an unbiased estimate of the causal effect of ventilators.</p>
<p>A useful identity to keep in mind is</p>
<p><span class="math display">\[
\underbrace{\text{difference in outcomes}}_{\text{what we observe}} = \underbrace{\text{causal effect}}_{\text{what we want}} + \underbrace{\text{selection bias}}_{\text{nuisance}}.
\]</span></p>
<p>Randomisation forces the second term on the right to zero on average. That is why <strong>Randomised Controlled Trials (RCTs)</strong> are considered the gold standard for establishing causality.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: private schools and test scores
</div>
</div>
<div class="callout-body-container callout-body">
<p>A study finds that students at private schools score higher on standardised tests. Can we conclude that private schools <em>cause</em> better performance? No — students at private schools tend to come from wealthier families with more resources at home, more educated parents, and so on. The “treatment” (attending a private school) is not randomly assigned, so the comparison is contaminated by selection.</p>
</div>
</div>
</section>
</section>
<section id="types-of-experiments" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="types-of-experiments"><span class="header-section-number">1.5</span> Types of experiments</h2>
<section id="randomised-experiments" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="randomised-experiments"><span class="header-section-number">1.5.1</span> Randomised experiments</h3>
<p>A randomised experiment assigns participants to two or more groups by lot: one group receives the intervention (the <strong>treatment</strong>); another serves as the <strong>control</strong> and receives a placebo or standard treatment. Randomisation ensures the groups are comparable, eliminates selection bias on average, and permits causal inference.</p>
<p>Genuine randomised experiments are common in clinical medicine but <strong>rare in economics and business</strong>, for two reasons:</p>
<ul>
<li><em>Ethical constraints</em> — we cannot randomly assign individuals to poverty, unemployment, or disease.</li>
<li><em>Cost</em> — well-designed field experiments are expensive and slow to run.</li>
</ul>
</section>
<section id="quasi-experiments" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="quasi-experiments"><span class="header-section-number">1.5.2</span> Quasi-experiments</h3>
<p>In a <strong>quasi-experiment</strong>, assignment to treatment is not random but is based on some <strong>observable</strong> criterion — often a threshold, an eligibility rule, or a policy change that hits some units but not others.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: a regional lockdown
</div>
</div>
<div class="callout-body-container callout-body">
<p>During the COVID-19 pandemic, lockdown (the treatment) was assigned by the <em>Junta de Andalucía</em> only to municipalities with infection rates above 1{,}000 per 100{,}000 inhabitants. Municipalities just above and just below the threshold are arguably similar, so comparing their outcomes can approximate a random experiment. We return to this kind of design later in the book.</p>
</div>
</div>
</section>
<section id="nonexperimental-observational-data" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="nonexperimental-observational-data"><span class="header-section-number">1.5.3</span> Nonexperimental (observational) data</h3>
<p>With <strong>nonexperimental</strong> data, all variables are collected simultaneously and the values are neither fixed nor repeatable by the researcher. Survey data are the classic example — the U.S. Current Population Survey (CPS) and the Spanish <em>Encuesta de Población Activa</em> (EPA) both belong to this category. Most of the datasets we use in this book are nonexperimental, which is precisely why the issue of selection bias matters so much.</p>
</section>
</section>
<section id="types-of-economic-data" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="types-of-economic-data"><span class="header-section-number">1.6</span> Types of economic data</h2>
<p>Economic data come in several “flavours”. Aggregation can be <em>micro</em> (households, firms, workers) or <em>macro</em> (regions, countries); variables can be <em>quantitative</em> (numbers) or <em>qualitative</em> (categories, e.g.&nbsp;employed / unemployed). For econometrics what matters most is the <strong>structure</strong> of the dataset: do we have one snapshot, a sequence over time, or repeated observations of the same units?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: cross-sectional data
</div>
</div>
<div class="callout-body-container callout-body">
<p>Data collected across sample units — individuals, firms, households, regions, countries — in a particular time period. Examples: income by Californian county in 2016; high-school graduation rates by U.S. state in 2015; the <code>wage1</code> dataset we use in the lab below.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: time-series data
</div>
</div>
<div class="callout-body-container callout-body">
<p>Data collected over discrete intervals of time, with the same economic quantity recorded at a regular frequency. Examples: the annual price of wheat, daily General Electric stock prices, monthly Spanish unemployment rates from 1980 to 2024.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: panel (longitudinal) data
</div>
</div>
<div class="callout-body-container callout-body">
<p>Observations on individual micro-units that are followed over multiple time periods. The defining feature is that <em>each</em> unit is observed in <em>several</em> periods. If every unit is observed in every period, the panel is <strong>balanced</strong>; otherwise it is <strong>unbalanced</strong>. Typically the number of time periods is small relative to the number of units, but not always.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: pooled cross-section
</div>
</div>
<div class="callout-body-container callout-body">
<p>Independent cross-sections drawn in different periods and stacked together. Different units are sampled each time — there is <em>no</em> re-interview of the same individuals — but the periods can be compared. The Spanish EPA, which draws a fresh independent sample of households every quarter, yields a pooled cross-section when several waves are stacked.</p>
</div>
</div>
<p>The data structure matters because it determines the questions we can answer. With a cross-section we can study how outcomes vary <em>across</em> units at one moment in time. With a time-series we can study how a single quantity evolves <em>over</em> time. With a panel we can do both — and, crucially, we can control for time-invariant unobserved characteristics of each unit, an important tool in modern causal inference. With a pooled cross-section we can study how a relationship changes between periods (for example, before and after a policy reform).</p>
</section>
<section id="lab-exploring-economic-data" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="lab-exploring-economic-data"><span class="header-section-number">1.7</span> Lab: exploring economic data</h2>
<p>The rest of the chapter is a guided exploration of the <code>wage1</code> dataset shipped with the <strong>wooldridge</strong> R package. The dataset is a <em>cross-section</em> of 526 U.S. workers observed in May 1976, with information on hourly wages, education, experience, tenure, and a handful of demographic variables. (The mechanics of installing R and the <code>wooldridge</code> package are covered in Appendix A; the first formal regression with <code>lm()</code> is the opening lab of Chapter 2.)</p>
<p>We start by loading the package and looking at the data.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="structure-size-and-a-first-look" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="structure-size-and-a-first-look"><span class="header-section-number">1.7.1</span> Structure, size, and a first look</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   526 obs. of  24 variables:
 $ wage    : num  3.1 3.24 3 6 5.3 ...
 $ educ    : int  11 12 11 8 12 16 18 12 12 17 ...
 $ exper   : int  2 22 2 44 7 9 15 5 26 22 ...
 $ tenure  : int  0 2 0 28 2 8 7 3 4 21 ...
 $ nonwhite: int  0 0 0 0 0 0 0 0 0 0 ...
 $ female  : int  1 1 0 0 0 0 0 1 1 0 ...
 $ married : int  0 1 0 1 1 1 0 0 0 1 ...
 $ numdep  : int  2 3 2 0 1 0 0 0 2 0 ...
 $ smsa    : int  1 1 0 1 0 1 1 1 1 1 ...
 $ northcen: int  0 0 0 0 0 0 0 0 0 0 ...
 $ south   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ west    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ construc: int  0 0 0 0 0 0 0 0 0 0 ...
 $ ndurman : int  0 0 0 0 0 0 0 0 0 0 ...
 $ trcommpu: int  0 0 0 0 0 0 0 0 0 0 ...
 $ trade   : int  0 0 1 0 0 0 1 0 1 0 ...
 $ services: int  0 1 0 0 0 0 0 0 0 0 ...
 $ profserv: int  0 0 0 0 0 1 0 0 0 0 ...
 $ profocc : int  0 0 0 0 0 1 1 1 1 1 ...
 $ clerocc : int  0 0 0 1 0 0 0 0 0 0 ...
 $ servocc : int  0 1 0 0 0 0 0 0 0 0 ...
 $ lwage   : num  1.13 1.18 1.1 1.79 1.67 ...
 $ expersq : int  4 484 4 1936 49 81 225 25 676 484 ...
 $ tenursq : int  0 4 0 784 4 64 49 9 16 441 ...
 - attr(*, "time.stamp")= chr "25 Jun 2011 23:03"</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  wage educ exper tenure nonwhite female married numdep smsa northcen south
1 3.10   11     2      0        0      1       0      2    1        0     0
2 3.24   12    22      2        0      1       1      3    1        0     0
3 3.00   11     2      0        0      0       0      2    0        0     0
4 6.00    8    44     28        0      0       1      0    1        0     0
5 5.30   12     7      2        0      0       1      1    0        0     0
6 8.75   16     9      8        0      0       1      0    1        0     0
  west construc ndurman trcommpu trade services profserv profocc clerocc
1    1        0       0        0     0        0        0       0       0
2    1        0       0        0     0        1        0       0       0
3    1        0       0        0     1        0        0       0       0
4    1        0       0        0     0        0        0       0       1
5    1        0       0        0     0        0        0       0       0
6    1        0       0        0     0        0        1       1       0
  servocc    lwage expersq tenursq
1       0 1.131402       4       0
2       1 1.175573     484       4
3       0 1.098612       4       0
4       0 1.791759    1936     784
5       0 1.667707      49       4
6       0 2.169054      81      64</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 526</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<p>The output of <code>str()</code> tells us that <code>wage1</code> is a data frame with 526 observations and 24 variables. Each row is one worker. The variables we care about most in this chapter are:</p>
<ul>
<li><code>wage</code> — hourly wage, in 1976 U.S. dollars,</li>
<li><code>educ</code> — years of schooling,</li>
<li><code>exper</code> — years of potential labour-market experience,</li>
<li><code>tenure</code> — years with the current employer,</li>
<li><code>female</code> — a dummy equal to 1 for women, 0 for men,</li>
<li><code>married</code> — a dummy equal to 1 for married workers.</li>
</ul>
</section>
<section id="summary-statistics-and-distributions" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="summary-statistics-and-distributions"><span class="header-section-number">1.7.2</span> Summary statistics and distributions</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"tenure"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      wage             educ           exper           tenure      
 Min.   : 0.530   Min.   : 0.00   Min.   : 1.00   Min.   : 0.000  
 1st Qu.: 3.330   1st Qu.:12.00   1st Qu.: 5.00   1st Qu.: 0.000  
 Median : 4.650   Median :12.00   Median :13.50   Median : 2.000  
 Mean   : 5.896   Mean   :12.56   Mean   :17.02   Mean   : 5.105  
 3rd Qu.: 6.880   3rd Qu.:14.00   3rd Qu.:26.00   3rd Qu.: 7.000  
 Max.   :24.980   Max.   :18.00   Max.   :51.00   Max.   :44.000  </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(wage1<span class="sc">$</span>wage)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.693086</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(wage1<span class="sc">$</span>educ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.769022</code></pre>
</div>
</div>
<p><code>summary()</code> gives us min, quartiles, mean, and max for each variable. The mean wage is about $5.90 per hour and the median is about $4.65; the mean exceeds the median, which suggests a <strong>right-skewed</strong> distribution — a long upper tail of high earners. A histogram makes the shape obvious:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>wage,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of hourly wages"</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Wage (USD / hour)"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-initial-concepts_files/figure-html/ch01-hist-wage-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of hourly wages in wage1 (1976 USD).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>educ,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of years of education"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Years of education"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="st">"lightgreen"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-initial-concepts_files/figure-html/ch01-hist-educ-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of years of education in wage1.</figcaption>
</figure>
</div>
</div>
</div>
<p>The education distribution piles up at 12 years (high-school completion) and 16 years (a four-year college degree), as one would expect for U.S. data from this era.</p>
</section>
<section id="frequency-tables" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="frequency-tables"><span class="header-section-number">1.7.3</span> Frequency tables</h3>
<p>For categorical or count-like variables, <code>table()</code> is more useful than <code>summary()</code>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(wage1<span class="sc">$</span>female)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
274 252 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(wage1<span class="sc">$</span>married)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
206 320 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(wage1<span class="sc">$</span>female) <span class="sc">/</span> <span class="fu">nrow</span>(wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.5209125 0.4790875 </code></pre>
</div>
</div>
<p>About 48% of the sample are women and 52% are men.</p>
</section>
<section id="a-first-scatter-plot" class="level3" data-number="1.7.4">
<h3 data-number="1.7.4" class="anchored" data-anchor-id="a-first-scatter-plot"><span class="header-section-number">1.7.4</span> A first scatter plot</h3>
<p>A natural starting question is: do workers with more education earn more?</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage1<span class="sc">$</span>educ, wage1<span class="sc">$</span>wage,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Years of education"</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Hourly wage (USD)"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Wage vs. education"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch  =</span> <span class="dv">16</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-initial-concepts_files/figure-html/ch01-scatter-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Wage versus years of education. Each dot is one of the 526 workers.</figcaption>
</figure>
</div>
</div>
</div>
<p>The cloud of points slopes upward: on average, more educated workers earn higher wages. We can quantify the linear association with the <strong>sample correlation</strong>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>educ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4059033</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>exper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1129034</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>educ, wage1<span class="sc">$</span>exper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2995418</code></pre>
</div>
</div>
<p>The correlation between wage and education is about <span class="math inline">\(0.41\)</span> — a clearly positive but far-from-perfect linear association. Two further patterns stand out:</p>
<ul>
<li>The correlation between wage and <em>experience</em> is positive but smaller than the correlation with education.</li>
<li>The correlation between <em>education</em> and <em>experience</em> is <strong>negative</strong>. This is not because schooling destroys experience — it reflects how individuals allocate time across the life cycle: more years in school mean fewer years in the workforce, mechanically. We will see in Chapter 3 that ignoring this kind of correlation among regressors can severely bias a simple regression of wage on education.</li>
</ul>
</section>
<section id="conditional-means-a-preview-of-regression" class="level3" data-number="1.7.5">
<h3 data-number="1.7.5" class="anchored" data-anchor-id="conditional-means-a-preview-of-regression"><span class="header-section-number">1.7.5</span> Conditional means: a preview of regression</h3>
<p>A cleaner way to look at the data is to compute the <strong>conditional mean</strong> of wages given another variable. <code>tapply()</code> does exactly that:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>female,  mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       0        1 
7.099489 4.587659 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>married, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       0        1 
4.843884 6.573469 </code></pre>
</div>
</div>
<p>Men earn about $7.10 per hour on average; women earn about $4.59. Married workers earn about $6.32 per hour; single workers about $5.16. These are <strong>raw, unconditional</strong> comparisons.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: reading a conditional mean as a causal effect
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 2.51-dollar gender gap and the 1.16-dollar marriage premium are <strong>conditional means</strong>, not causal effects. The men and women in this sample differ in occupation, sector, experience, hours worked, and many other characteristics; married and single workers differ in age and tenure. Without holding those confounders fixed, neither gap can be interpreted as the <em>ceteris paribus</em> effect of gender or marriage on wages. Holding confounders fixed is what multiple regression (Chapter 3) is for.</p>
</div>
</div>
<p>A more striking selection-bias illustration uses the conditional mean of <em>experience</em> given <em>education</em>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>exper, wage1<span class="sc">$</span>educ, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       0        2        3        4        5        6        7        8 
32.00000 39.00000 51.00000 41.00000 34.00000 30.50000 31.25000 31.40909 
       9       10       11       12       13       14       15       16 
15.94118 14.83333 13.93103 18.14646 14.89744 16.13208 13.38095 12.35294 
      17       18 
13.33333 11.10526 </code></pre>
</div>
</div>
<p>Workers with little schooling have <em>more</em> labour-market experience, and workers with a college degree have <em>less</em>. So when we compare wages across education levels, we are simultaneously comparing workers who differ in experience — the comparison is confounded. This is the same kind of selection problem we saw in the ventilator and private-school examples, now in our actual dataset. We will fix it in Chapter 3 by including both <code>educ</code> and <code>exper</code> in a multiple regression.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why <code>wage1</code> is a cross-section
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>wage1</code> records each worker <strong>once</strong>, all in 1976. There is no time index, no person identifier observed in several years. It is a clean cross-section. With this dataset alone we <em>cannot</em> track how a given worker’s wage grows from one year to the next — that would require a <em>panel</em>, e.g.&nbsp;the U.S. Panel Study of Income Dynamics (PSID) or the Spanish <em>Muestra Continua de Vidas Laborales</em> (MCVL). Knowing what your data <em>can</em> and <em>cannot</em> tell you is half of applied econometrics.</p>
</div>
</div>
</section>
</section>
<section id="self-check" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="self-check">Self-check</h2>
<p>Eight short multiple-choice questions. Try each one before opening the answer.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q1. What is an econometric model?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>An econometric model differs from a purely economic (theoretical) model in that:</p>
<ul>
<li>A. It assumes the relationship between variables is exact and deterministic.</li>
<li>B. It adds a stochastic error term and a functional form so that unknown parameters can be estimated from data.</li>
<li>C. It does not require a sample of data because the parameters are derived from theory.</li>
<li>D. It is only used in macroeconomic problems, not in microeconomic ones.</li>
</ul>
<p><strong>Answer: B.</strong> An econometric model couples a functional form with a random disturbance <span class="math inline">\(u\)</span>, which makes the unknown parameters estimable from observed data.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q2. The role of the error term
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the population regression model <span class="math inline">\(y = \beta_0 + \beta_1 x + u\)</span>, the error term <span class="math inline">\(u\)</span>:</p>
<ul>
<li>A. Is the difference between <span class="math inline">\(y_i\)</span> and the OLS fitted value <span class="math inline">\(\hat y_i\)</span> in our sample.</li>
<li>B. Is always equal to zero in the population.</li>
<li>C. Captures every factor — other than <span class="math inline">\(x\)</span> — that influences <span class="math inline">\(y\)</span>.</li>
<li>D. Is observable as soon as we have data on <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>.</li>
</ul>
<p><strong>Answer: C.</strong> <span class="math inline">\(u\)</span> is a <em>population</em>, <em>unobservable</em> quantity collecting all omitted determinants of <span class="math inline">\(y\)</span>. The residual <span class="math inline">\(\hat u_i\)</span> is its sample counterpart, computed only after estimation.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q3. Cross-section or not?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A dataset with information on 526 workers interviewed in May 1976 (one observation per worker, all measured at the same time) is:</p>
<ul>
<li>A. Cross-sectional data.</li>
<li>B. Time-series data.</li>
<li>C. Panel (longitudinal) data.</li>
<li>D. Pooled cross-section data.</li>
</ul>
<p><strong>Answer: A.</strong> Many units, one time period, no repeated observation of the same unit — the textbook definition of a cross-section.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q4. Time series
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Annual Spanish unemployment rates from 1980 to 2024 are an example of:</p>
<ul>
<li>A. Cross-sectional data.</li>
<li>B. Time-series data.</li>
<li>C. Panel data.</li>
<li>D. Experimental data.</li>
</ul>
<p><strong>Answer: B.</strong> One quantity (the unemployment rate) recorded at a regular frequency over time.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q5. Panel vs pooled cross-section
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A dataset follows 1{,}000 firms during the years 2010–2024, recording sales, employment and exports for each firm in every year. This is:</p>
<ul>
<li>A. Cross-sectional data, since each firm-year is one row.</li>
<li>B. Pooled cross-section, since different units are sampled in each period.</li>
<li>C. Time-series data, since it has a time dimension.</li>
<li>D. Panel (longitudinal) data: the same units observed repeatedly over time.</li>
</ul>
<p><strong>Answer: D.</strong> The same firms are tracked over multiple periods, which is exactly the panel structure.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q6. What does correlation tell us?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A high positive correlation between two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> implies that:</p>
<ul>
<li>A. <span class="math inline">\(X\)</span> causes <span class="math inline">\(Y\)</span>.</li>
<li>B. <span class="math inline">\(Y\)</span> causes <span class="math inline">\(X\)</span>.</li>
<li>C. There exists a deterministic linear relationship between them.</li>
<li>D. They tend to move together, but this association may be driven by a third variable, by reverse causality, or by selection.</li>
</ul>
<p><strong>Answer: D.</strong> Correlation is silent about causal direction or confounding. The ice-cream-and-drowning example in §1.4.2 is the canonical warning.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q7. Selection bias
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Selection bias arises when:</p>
<ul>
<li>A. The units that select into the treatment group differ systematically from those that do not, even before treatment.</li>
<li>B. The researcher chooses regressors based on <span class="math inline">\(t\)</span>-statistics.</li>
<li>C. The sample size is too small to detect a true effect.</li>
<li>D. The dependent variable is measured with error.</li>
</ul>
<p><strong>Answer: A.</strong> Selection bias is a property of the <em>assignment</em> of treatment, not of estimation or measurement. The ventilator example in §1.4.1 is the prototype.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Q8. Randomisation as a remedy
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In which of the following research designs does randomisation <em>by construction</em> eliminate selection bias?</p>
<ul>
<li>A. Comparing employed vs.&nbsp;unemployed individuals using cross-sectional survey data.</li>
<li>B. A randomised controlled trial (RCT) where the treatment is assigned by lottery.</li>
<li>C. Comparing students who chose to enrol in a private vs.&nbsp;a public school.</li>
<li>D. Comparing countries that adopted the euro vs.&nbsp;countries that did not.</li>
</ul>
<p><strong>Answer: B.</strong> Only random assignment guarantees that, <em>on average</em>, treated and untreated units have the same pre-treatment characteristics.</p>
</div>
</div>
</div>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p><strong>Exercise 1.1 ★ — Classifying datasets.</strong> Classify each of the following datasets as cross-sectional, time-series, panel, or pooled cross-section.</p>
<ol type="a">
<li>Monthly Spanish CPI from 1980 to 2024.</li>
<li><code>wage1</code>: 526 workers interviewed in May 1976, one row per worker.</li>
<li>The Spanish EPA: each quarter, a fresh independent sample of households is drawn (no household is revisited); several quarters are then stacked.</li>
<li>A dataset that follows the same 800 students from age 6 to age 18, recording their test scores every year.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Time-series. (b) Cross-sectional. (c) Pooled cross-section — new units each period. (d) Panel: the <em>same</em> units are followed over multiple periods.</li>
</ol>
</div>
</div>
</div>
<p><strong>Exercise 1.2 ★ — Spotting selection bias.</strong> For each scenario, state whether selection bias is a likely problem, and identify which characteristic drives the selection.</p>
<ol type="a">
<li>A hospital compares mortality of patients who received a ventilator with patients who did not.</li>
<li>An economist compares the wages of workers who completed a job-training programme with the wages of workers who did not enrol.</li>
<li>Researchers compare countries that adopted the euro in 1999 with countries that did not.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Yes — severity of illness drives both ventilator assignment and mortality. (b) Yes — self-selection into training is driven by motivation, prior earnings, and labour-market prospects, all of which also affect wages. (c) Yes — countries that joined the euro were chosen on the basis of macroeconomic fundamentals (the Maastricht criteria), so they are not a random sample of European countries.</li>
</ol>
</div>
</div>
</div>
<p><strong>Exercise 1.3 ★★ — Sign of an omitted-variable bias.</strong> Suppose you regress hourly wage on years of education in a sample of currently employed adults, <em>without</em> controlling for innate ability. Assume that (i) more able workers earn more, holding education fixed, and (ii) more able workers tend to acquire more education. Will the coefficient on <code>educ</code> be biased upward (too positive) or downward (too negative)? Explain in one sentence.</p>
<p><em>A full answer is given in the Instructor Edition.</em></p>
<p><strong>Exercise 1.4 ★★ — Designing a randomised experiment.</strong> You want to know whether a free university preparation course (the treatment) causally raises the probability that high-school students from low-income families enrol in university. Sketch the design of a randomised experiment that would identify this causal effect. Be explicit about: the population, the assignment rule, the treatment and control groups, the outcome variable, and the time horizon. Briefly discuss one ethical objection your design will have to address.</p>
<p><em>A full answer is given in the Instructor Edition.</em></p>
<p><strong>Exercise 1.5 ★★ — A naive omitted-variable model.</strong> A worker’s wage is generated by</p>
<p><span class="math display">\[
w = 5 + 2 \cdot \mathit{edu} + u, \qquad \mathbb{E}[u] = 0,\ \operatorname{Var}(u) = 1,
\]</span></p>
<p>where <span class="math inline">\(\mathit{edu}\in\{0,1,2,3\}\)</span> are years of post-compulsory education. Suppose that ability (collected in <span class="math inline">\(u\)</span>) is correlated with education: <span class="math inline">\(\mathbb{E}[u\mid \mathit{edu}] = 0.5\cdot \mathit{edu}\)</span>.</p>
<ol type="a">
<li>Compute <span class="math inline">\(\mathbb{E}[w\mid \mathit{edu}]\)</span>.</li>
<li>If we naively assume <span class="math inline">\(\mathbb{E}[u\mid \mathit{edu}] = 0\)</span> and read off the slope, what do we get? By how much do we <em>miss</em> the true marginal effect of an extra year of education?</li>
</ol>
<p><em>A full answer is given in the Instructor Edition.</em></p>
<p><strong>Exercise 1.6 ★★★ — Chocolate and Nobel prizes.</strong> It has been documented <span class="citation" data-cites="cgl2017">(<a href="#ref-cgl2017" role="doc-biblioref">Hill et al. 2017</a>)</span> that countries with higher per-capita chocolate consumption also win more Nobel prizes per capita. Is this evidence that chocolate consumption <em>causes</em> Nobel prizes? Identify (i) at least one plausible omitted variable, (ii) at least one alternative causal channel (reverse causation, selection of which countries get measured, etc.), and (iii) describe a <em>hypothetical</em> research design — experimental or quasi-experimental — that would allow you to learn the causal effect of chocolate on prize-winning. Be honest about why this design is unlikely to be feasible.</p>
<p><em>A full answer is given in the Instructor Edition.</em></p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-cgl2017" class="csl-entry" role="listitem">
Hill, R. Carter, William E. Griffiths, and Guay C. Lim. 2017. <em>Principles of Econometrics</em>. 5th ed. Wiley.
</div>
<div id="ref-wooldridge2020" class="csl-entry" role="listitem">
Wooldridge, Jeffrey M. 2020. <em>Introductory Econometrics: A Modern Approach</em>. 7th ed. Cengage Learning.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/02-simple-regression.html" class="pagination-link" aria-label="The Simple Linear Regression Model">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Simple Linear Regression Model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Initial Concepts"</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning outcomes {.unnumbered}</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>By the end of this chapter the reader should be able to:</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Explain what econometrics is and how an econometric model differs from a purely theoretical economic model.</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Interpret the two components of an econometric model: the systematic part and the random error $u$.</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Distinguish correlation from causation, and identify selection bias and omitted-variable bias in concrete examples.</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Explain why randomisation eliminates selection bias on average, and contrast randomised experiments with quasi-experimental and observational designs.</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Classify a dataset as cross-sectional, time-series, panel, or pooled cross-section, and recognise the research questions each structure can (and cannot) answer.</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Use basic R commands (<span class="in">`str()`</span>, <span class="in">`summary()`</span>, <span class="in">`head()`</span>, <span class="in">`hist()`</span>, <span class="in">`plot()`</span>, <span class="in">`tapply()`</span>, <span class="in">`cor()`</span>) to explore a microeconomic dataset and compute conditional means.</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Motivating empirical question {.unnumbered}</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *Does going to university **cause** higher wages, or do the people who would have earned more anyway tend to go to university?*</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>This single question drives the rest of the course. A correlation between schooling and wages is easy to compute; turning that correlation into a credible statement about the causal return to education is hard. The tools we develop --- the linear model, the assumptions on the error term, randomisation, controls, and tests --- are all in the service of answering questions of this form.</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## What is econometrics?</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a><span class="in">`\lettrine[lines=3]{E}{conometrics}`</span>{=latex} is the application of statistical methods to economic data, with the goal of giving empirical content to economic relationships <span class="co">[</span><span class="ot">@wooldridge2020; @cgl2017</span><span class="co">]</span>. Its main objective is the **estimation of relationships between variables**. Typical pairs of interest in this course include:</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Education $\Rightarrow$ Salary</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Class attendance $\Rightarrow$ Final grade</span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Tuition fees $\Rightarrow$ Enrolment</span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Income $\Rightarrow$ Happiness</span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Government spending $\Rightarrow$ Crime</span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Advertising $\Rightarrow$ Sales</span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>In general we write $X \Rightarrow Y$, where $X$ is the **independent variable** (or regressor, explanatory variable) and $Y$ is the **dependent variable** (or response, outcome). Two questions then arise:</span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Is there an effect of $X$ on $Y$?</span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>How large is that effect?</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>These "how much" questions are everywhere. A city council wonders how much violent crime will fall if it spends an additional million euros on policing. A local business must estimate the relationship between advertising spending and sales. A university must estimate how much enrolment will drop if it raises tuition by 300 euros. None of these questions can be answered by economic theory alone --- they require data, a statistical model, and the discipline of econometrics.</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## The econometric model</span></span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a>An econometric model has **two** components:</span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>A **systematic component** --- the average or systematic behaviour of many individuals, firms, or other units.</span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>A **random error** $u$ (sometimes called the *disturbance*) --- the many factors that affect $Y$ but are not included in the systematic part.</span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-48"><a href="#cb37-48" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-49"><a href="#cb37-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: salary determination</span></span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a>The factors associated with an individual's salary include age, gender, experience, and education. In general functional form:</span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a>\text{Salary} = f(\text{Age},\,\text{Gender},\,\text{Experience},\,\text{Education}) + u.</span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a>A linear specification is</span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a>\text{Salary} = \beta_0 + \beta_1\,\text{Age} + \beta_2\,\text{Gender} + \beta_3\,\text{Experience} + \beta_4\,\text{Education} + u.</span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a>The coefficients $\beta_0, \beta_1, \dots, \beta_4$ are **unknown population parameters** that we will estimate from data using an econometric technique (typically Ordinary Least Squares, introduced in Chapter 2).</span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-65"><a href="#cb37-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-66"><a href="#cb37-66" aria-hidden="true" tabindex="-1"></a>The functional form is itself a hypothesis about how the variables are connected. A key challenge in any applied problem is choosing a functional form that is compatible both with economic theory and with what the data look like.</span>
<span id="cb37-67"><a href="#cb37-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-68"><a href="#cb37-68" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning}</span>
<span id="cb37-69"><a href="#cb37-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## Common mistake: confusing $u$ with the residual $\hat u$</span></span>
<span id="cb37-70"><a href="#cb37-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-71"><a href="#cb37-71" aria-hidden="true" tabindex="-1"></a>The error $u$ is a *population* object: it represents every determinant of $Y$ that is not in the model, and it is **unobservable**. The residual $\hat u_i = y_i - \hat y_i$ is its *sample* counterpart, obtained after estimating the model. Following Wooldridge's notation, we keep $u$ and $\hat u$ strictly separate throughout the book.</span>
<span id="cb37-72"><a href="#cb37-72" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-73"><a href="#cb37-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-74"><a href="#cb37-74" aria-hidden="true" tabindex="-1"></a><span class="fu">## Uses of econometrics</span></span>
<span id="cb37-75"><a href="#cb37-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-76"><a href="#cb37-76" aria-hidden="true" tabindex="-1"></a>We use econometric models for three broad purposes:</span>
<span id="cb37-77"><a href="#cb37-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-78"><a href="#cb37-78" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Test economic theories and hypotheses.** For example: does increasing the minimum wage reduce employment? Does class attendance improve grades?</span>
<span id="cb37-79"><a href="#cb37-79" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Predict economic variables.** For example: forecast next quarter's GDP growth, or tomorrow's electricity demand.</span>
<span id="cb37-80"><a href="#cb37-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Estimate causal relationships.** For example: does an additional year of education *cause* higher wages, or are educated workers simply different to begin with?</span>
<span id="cb37-81"><a href="#cb37-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-82"><a href="#cb37-82" aria-hidden="true" tabindex="-1"></a>The third use --- credible causal inference from observational data --- is at the heart of the so-called **Credibility Revolution** in empirical economics. Hypothesis testing and prediction are sometimes called "Led Zeppelin" econometrics; causal inference is the modern emphasis <span class="co">[</span><span class="ot">@cgl2017</span><span class="co">]</span>.</span>
<span id="cb37-83"><a href="#cb37-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-84"><a href="#cb37-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## Correlation does not imply causation</span></span>
<span id="cb37-85"><a href="#cb37-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-86"><a href="#cb37-86" aria-hidden="true" tabindex="-1"></a>One of the most important lessons of the course --- repeated, if necessary, on every page --- is that **correlation does not imply causation**. The fact that two variables move together does not establish that one of them causes the other. Two reasons stand out: *selection bias* and *omitted variables*.</span>
<span id="cb37-87"><a href="#cb37-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-88"><a href="#cb37-88" aria-hidden="true" tabindex="-1"></a><span class="fu">### Selection bias</span></span>
<span id="cb37-89"><a href="#cb37-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-90"><a href="#cb37-90" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-91"><a href="#cb37-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: ventilators and deaths</span></span>
<span id="cb37-92"><a href="#cb37-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-93"><a href="#cb37-93" aria-hidden="true" tabindex="-1"></a>A hospital wants to know whether ventilators save lives. A naive comparison shows that patients on ventilators die *more* often than patients not on ventilators. Should we conclude that ventilators *kill* patients?</span>
<span id="cb37-94"><a href="#cb37-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-95"><a href="#cb37-95" aria-hidden="true" tabindex="-1"></a>Obviously not. The problem is **selection bias**: the sickest patients are precisely the ones who are placed on a ventilator. These patients would have had a higher mortality rate *regardless* of whether they received a ventilator.</span>
<span id="cb37-96"><a href="#cb37-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-97"><a href="#cb37-97" aria-hidden="true" tabindex="-1"></a>The observed correlation between ventilator use and death is *positive*; the true causal effect of ventilators on survival is *negative*. A naive comparison can therefore give us not just the wrong magnitude but the **wrong sign** of the effect.</span>
<span id="cb37-98"><a href="#cb37-98" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-99"><a href="#cb37-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-100"><a href="#cb37-100" aria-hidden="true" tabindex="-1"></a>The lesson is general: whenever treatment is not assigned randomly, simple comparisons of outcomes between treated and untreated units confound the causal effect of the treatment with the characteristics of the units that selected into it.</span>
<span id="cb37-101"><a href="#cb37-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-102"><a href="#cb37-102" aria-hidden="true" tabindex="-1"></a><span class="fu">### Omitted variable bias</span></span>
<span id="cb37-103"><a href="#cb37-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-104"><a href="#cb37-104" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-105"><a href="#cb37-105" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: ice cream and drowning</span></span>
<span id="cb37-106"><a href="#cb37-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-107"><a href="#cb37-107" aria-hidden="true" tabindex="-1"></a>Data show a strong positive correlation between ice-cream sales and drowning deaths. Should we ban ice cream to prevent drowning?</span>
<span id="cb37-108"><a href="#cb37-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-109"><a href="#cb37-109" aria-hidden="true" tabindex="-1"></a>Of course not. The **omitted variable** is *temperature*. Hot weather causes both more ice-cream sales and more swimming (hence more drowning). Without controlling for temperature, the correlation between ice cream and drowning is a **spurious correlation** --- a real statistical association with no causal content.</span>
<span id="cb37-110"><a href="#cb37-110" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-111"><a href="#cb37-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-112"><a href="#cb37-112" aria-hidden="true" tabindex="-1"></a>Whenever a variable that influences $Y$ is also correlated with $X$ but is left out of the model, the estimate of the effect of $X$ will be biased. We will study this formally as **omitted variable bias** in Chapter 3.</span>
<span id="cb37-113"><a href="#cb37-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-114"><a href="#cb37-114" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why randomisation solves the problem</span></span>
<span id="cb37-115"><a href="#cb37-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-116"><a href="#cb37-116" aria-hidden="true" tabindex="-1"></a>If we **randomly** assign individuals to a treatment group and a control group, then on average the two groups will have the same observable and unobservable characteristics *before* the treatment is administered. Any difference in outcomes *after* the treatment can therefore be attributed to the treatment itself.</span>
<span id="cb37-117"><a href="#cb37-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-118"><a href="#cb37-118" aria-hidden="true" tabindex="-1"></a>In the ventilator example, if we could randomly assign ventilators (not based on severity of illness), then the treatment and control groups would have the same average severity. The difference in mortality between the two groups would be an unbiased estimate of the causal effect of ventilators.</span>
<span id="cb37-119"><a href="#cb37-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-120"><a href="#cb37-120" aria-hidden="true" tabindex="-1"></a>A useful identity to keep in mind is</span>
<span id="cb37-121"><a href="#cb37-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-122"><a href="#cb37-122" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-123"><a href="#cb37-123" aria-hidden="true" tabindex="-1"></a>\underbrace{\text{difference in outcomes}}_{\text{what we observe}} = \underbrace{\text{causal effect}}_{\text{what we want}} + \underbrace{\text{selection bias}}_{\text{nuisance}}.</span>
<span id="cb37-124"><a href="#cb37-124" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-125"><a href="#cb37-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-126"><a href="#cb37-126" aria-hidden="true" tabindex="-1"></a>Randomisation forces the second term on the right to zero on average. That is why **Randomised Controlled Trials (RCTs)** are considered the gold standard for establishing causality.</span>
<span id="cb37-127"><a href="#cb37-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-128"><a href="#cb37-128" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-129"><a href="#cb37-129" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: private schools and test scores</span></span>
<span id="cb37-130"><a href="#cb37-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-131"><a href="#cb37-131" aria-hidden="true" tabindex="-1"></a>A study finds that students at private schools score higher on standardised tests. Can we conclude that private schools *cause* better performance? No --- students at private schools tend to come from wealthier families with more resources at home, more educated parents, and so on. The "treatment" (attending a private school) is not randomly assigned, so the comparison is contaminated by selection.</span>
<span id="cb37-132"><a href="#cb37-132" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-133"><a href="#cb37-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-134"><a href="#cb37-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Types of experiments</span></span>
<span id="cb37-135"><a href="#cb37-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-136"><a href="#cb37-136" aria-hidden="true" tabindex="-1"></a><span class="fu">### Randomised experiments</span></span>
<span id="cb37-137"><a href="#cb37-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-138"><a href="#cb37-138" aria-hidden="true" tabindex="-1"></a>A randomised experiment assigns participants to two or more groups by lot: one group receives the intervention (the **treatment**); another serves as the **control** and receives a placebo or standard treatment. Randomisation ensures the groups are comparable, eliminates selection bias on average, and permits causal inference.</span>
<span id="cb37-139"><a href="#cb37-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-140"><a href="#cb37-140" aria-hidden="true" tabindex="-1"></a>Genuine randomised experiments are common in clinical medicine but **rare in economics and business**, for two reasons:</span>
<span id="cb37-141"><a href="#cb37-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-142"><a href="#cb37-142" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>*Ethical constraints* --- we cannot randomly assign individuals to poverty, unemployment, or disease.</span>
<span id="cb37-143"><a href="#cb37-143" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>*Cost* --- well-designed field experiments are expensive and slow to run.</span>
<span id="cb37-144"><a href="#cb37-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-145"><a href="#cb37-145" aria-hidden="true" tabindex="-1"></a><span class="fu">### Quasi-experiments</span></span>
<span id="cb37-146"><a href="#cb37-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-147"><a href="#cb37-147" aria-hidden="true" tabindex="-1"></a>In a **quasi-experiment**, assignment to treatment is not random but is based on some **observable** criterion --- often a threshold, an eligibility rule, or a policy change that hits some units but not others.</span>
<span id="cb37-148"><a href="#cb37-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-149"><a href="#cb37-149" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-150"><a href="#cb37-150" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: a regional lockdown</span></span>
<span id="cb37-151"><a href="#cb37-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-152"><a href="#cb37-152" aria-hidden="true" tabindex="-1"></a>During the COVID-19 pandemic, lockdown (the treatment) was assigned by the *Junta de Andalucía* only to municipalities with infection rates above 1{,}000 per 100{,}000 inhabitants. Municipalities just above and just below the threshold are arguably similar, so comparing their outcomes can approximate a random experiment. We return to this kind of design later in the book.</span>
<span id="cb37-153"><a href="#cb37-153" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-154"><a href="#cb37-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-155"><a href="#cb37-155" aria-hidden="true" tabindex="-1"></a><span class="fu">### Nonexperimental (observational) data</span></span>
<span id="cb37-156"><a href="#cb37-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-157"><a href="#cb37-157" aria-hidden="true" tabindex="-1"></a>With **nonexperimental** data, all variables are collected simultaneously and the values are neither fixed nor repeatable by the researcher. Survey data are the classic example --- the U.S. Current Population Survey (CPS) and the Spanish *Encuesta de Población Activa* (EPA) both belong to this category. Most of the datasets we use in this book are nonexperimental, which is precisely why the issue of selection bias matters so much.</span>
<span id="cb37-158"><a href="#cb37-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-159"><a href="#cb37-159" aria-hidden="true" tabindex="-1"></a><span class="fu">## Types of economic data</span></span>
<span id="cb37-160"><a href="#cb37-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-161"><a href="#cb37-161" aria-hidden="true" tabindex="-1"></a>Economic data come in several "flavours". Aggregation can be *micro* (households, firms, workers) or *macro* (regions, countries); variables can be *quantitative* (numbers) or *qualitative* (categories, e.g. employed / unemployed). For econometrics what matters most is the **structure** of the dataset: do we have one snapshot, a sequence over time, or repeated observations of the same units?</span>
<span id="cb37-162"><a href="#cb37-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-163"><a href="#cb37-163" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-164"><a href="#cb37-164" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definition: cross-sectional data</span></span>
<span id="cb37-165"><a href="#cb37-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-166"><a href="#cb37-166" aria-hidden="true" tabindex="-1"></a>Data collected across sample units --- individuals, firms, households, regions, countries --- in a particular time period. Examples: income by Californian county in 2016; high-school graduation rates by U.S. state in 2015; the <span class="in">`wage1`</span> dataset we use in the lab below.</span>
<span id="cb37-167"><a href="#cb37-167" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-168"><a href="#cb37-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-169"><a href="#cb37-169" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-170"><a href="#cb37-170" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definition: time-series data</span></span>
<span id="cb37-171"><a href="#cb37-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-172"><a href="#cb37-172" aria-hidden="true" tabindex="-1"></a>Data collected over discrete intervals of time, with the same economic quantity recorded at a regular frequency. Examples: the annual price of wheat, daily General Electric stock prices, monthly Spanish unemployment rates from 1980 to 2024.</span>
<span id="cb37-173"><a href="#cb37-173" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-174"><a href="#cb37-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-175"><a href="#cb37-175" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-176"><a href="#cb37-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definition: panel (longitudinal) data</span></span>
<span id="cb37-177"><a href="#cb37-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-178"><a href="#cb37-178" aria-hidden="true" tabindex="-1"></a>Observations on individual micro-units that are followed over multiple time periods. The defining feature is that *each* unit is observed in *several* periods. If every unit is observed in every period, the panel is **balanced**; otherwise it is **unbalanced**. Typically the number of time periods is small relative to the number of units, but not always.</span>
<span id="cb37-179"><a href="#cb37-179" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-180"><a href="#cb37-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-181"><a href="#cb37-181" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-182"><a href="#cb37-182" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definition: pooled cross-section</span></span>
<span id="cb37-183"><a href="#cb37-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-184"><a href="#cb37-184" aria-hidden="true" tabindex="-1"></a>Independent cross-sections drawn in different periods and stacked together. Different units are sampled each time --- there is *no* re-interview of the same individuals --- but the periods can be compared. The Spanish EPA, which draws a fresh independent sample of households every quarter, yields a pooled cross-section when several waves are stacked.</span>
<span id="cb37-185"><a href="#cb37-185" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-186"><a href="#cb37-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-187"><a href="#cb37-187" aria-hidden="true" tabindex="-1"></a>The data structure matters because it determines the questions we can answer. With a cross-section we can study how outcomes vary *across* units at one moment in time. With a time-series we can study how a single quantity evolves *over* time. With a panel we can do both --- and, crucially, we can control for time-invariant unobserved characteristics of each unit, an important tool in modern causal inference. With a pooled cross-section we can study how a relationship changes between periods (for example, before and after a policy reform).</span>
<span id="cb37-188"><a href="#cb37-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-189"><a href="#cb37-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## Lab: exploring economic data</span></span>
<span id="cb37-190"><a href="#cb37-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-191"><a href="#cb37-191" aria-hidden="true" tabindex="-1"></a>The rest of the chapter is a guided exploration of the <span class="in">`wage1`</span> dataset shipped with the **wooldridge** R package. The dataset is a *cross-section* of 526 U.S. workers observed in May 1976, with information on hourly wages, education, experience, tenure, and a handful of demographic variables. (The mechanics of installing R and the <span class="in">`wooldridge`</span> package are covered in Appendix A; the first formal regression with <span class="in">`lm()`</span> is the opening lab of Chapter 2.)</span>
<span id="cb37-192"><a href="#cb37-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-193"><a href="#cb37-193" aria-hidden="true" tabindex="-1"></a>We start by loading the package and looking at the data.</span>
<span id="cb37-194"><a href="#cb37-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-195"><a href="#cb37-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-setup}</span></span>
<span id="cb37-196"><a href="#cb37-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb37-197"><a href="#cb37-197" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb37-198"><a href="#cb37-198" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>)</span>
<span id="cb37-199"><a href="#cb37-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-200"><a href="#cb37-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-201"><a href="#cb37-201" aria-hidden="true" tabindex="-1"></a><span class="fu">### Structure, size, and a first look</span></span>
<span id="cb37-202"><a href="#cb37-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-203"><a href="#cb37-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-structure}</span></span>
<span id="cb37-204"><a href="#cb37-204" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wage1)</span>
<span id="cb37-205"><a href="#cb37-205" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wage1)</span>
<span id="cb37-206"><a href="#cb37-206" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(wage1)</span>
<span id="cb37-207"><a href="#cb37-207" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(wage1)</span>
<span id="cb37-208"><a href="#cb37-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-209"><a href="#cb37-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-210"><a href="#cb37-210" aria-hidden="true" tabindex="-1"></a>The output of <span class="in">`str()`</span> tells us that <span class="in">`wage1`</span> is a data frame with <span class="in">`r nrow(wage1)`</span> observations and <span class="in">`r ncol(wage1)`</span> variables. Each row is one worker. The variables we care about most in this chapter are:</span>
<span id="cb37-211"><a href="#cb37-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-212"><a href="#cb37-212" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`wage`</span> --- hourly wage, in 1976 U.S. dollars,</span>
<span id="cb37-213"><a href="#cb37-213" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`educ`</span> --- years of schooling,</span>
<span id="cb37-214"><a href="#cb37-214" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`exper`</span> --- years of potential labour-market experience,</span>
<span id="cb37-215"><a href="#cb37-215" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`tenure`</span> --- years with the current employer,</span>
<span id="cb37-216"><a href="#cb37-216" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`female`</span> --- a dummy equal to 1 for women, 0 for men,</span>
<span id="cb37-217"><a href="#cb37-217" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`married`</span> --- a dummy equal to 1 for married workers.</span>
<span id="cb37-218"><a href="#cb37-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-219"><a href="#cb37-219" aria-hidden="true" tabindex="-1"></a><span class="fu">### Summary statistics and distributions</span></span>
<span id="cb37-220"><a href="#cb37-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-221"><a href="#cb37-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-summary}</span></span>
<span id="cb37-222"><a href="#cb37-222" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage1[, <span class="fu">c</span>(<span class="st">"wage"</span>, <span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"tenure"</span>)])</span>
<span id="cb37-223"><a href="#cb37-223" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(wage1<span class="sc">$</span>wage)</span>
<span id="cb37-224"><a href="#cb37-224" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(wage1<span class="sc">$</span>educ)</span>
<span id="cb37-225"><a href="#cb37-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-226"><a href="#cb37-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-227"><a href="#cb37-227" aria-hidden="true" tabindex="-1"></a><span class="in">`summary()`</span> gives us min, quartiles, mean, and max for each variable. The mean wage is about $5.90 per hour and the median is about $4.65; the mean exceeds the median, which suggests a **right-skewed** distribution --- a long upper tail of high earners. A histogram makes the shape obvious:</span>
<span id="cb37-228"><a href="#cb37-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-229"><a href="#cb37-229" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-hist-wage}</span></span>
<span id="cb37-230"><a href="#cb37-230" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribution of hourly wages in wage1 (1976 USD)."</span></span>
<span id="cb37-231"><a href="#cb37-231" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>wage,</span>
<span id="cb37-232"><a href="#cb37-232" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of hourly wages"</span>,</span>
<span id="cb37-233"><a href="#cb37-233" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Wage (USD / hour)"</span>,</span>
<span id="cb37-234"><a href="#cb37-234" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb37-235"><a href="#cb37-235" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>)</span>
<span id="cb37-236"><a href="#cb37-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-237"><a href="#cb37-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-238"><a href="#cb37-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-hist-educ}</span></span>
<span id="cb37-239"><a href="#cb37-239" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribution of years of education in wage1."</span></span>
<span id="cb37-240"><a href="#cb37-240" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>educ,</span>
<span id="cb37-241"><a href="#cb37-241" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of years of education"</span>,</span>
<span id="cb37-242"><a href="#cb37-242" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Years of education"</span>,</span>
<span id="cb37-243"><a href="#cb37-243" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="st">"lightgreen"</span>,</span>
<span id="cb37-244"><a href="#cb37-244" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>)</span>
<span id="cb37-245"><a href="#cb37-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-246"><a href="#cb37-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-247"><a href="#cb37-247" aria-hidden="true" tabindex="-1"></a>The education distribution piles up at 12 years (high-school completion) and 16 years (a four-year college degree), as one would expect for U.S. data from this era.</span>
<span id="cb37-248"><a href="#cb37-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-249"><a href="#cb37-249" aria-hidden="true" tabindex="-1"></a><span class="fu">### Frequency tables</span></span>
<span id="cb37-250"><a href="#cb37-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-251"><a href="#cb37-251" aria-hidden="true" tabindex="-1"></a>For categorical or count-like variables, <span class="in">`table()`</span> is more useful than <span class="in">`summary()`</span>:</span>
<span id="cb37-252"><a href="#cb37-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-253"><a href="#cb37-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-tables}</span></span>
<span id="cb37-254"><a href="#cb37-254" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(wage1<span class="sc">$</span>female)</span>
<span id="cb37-255"><a href="#cb37-255" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(wage1<span class="sc">$</span>married)</span>
<span id="cb37-256"><a href="#cb37-256" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(wage1<span class="sc">$</span>female) <span class="sc">/</span> <span class="fu">nrow</span>(wage1)</span>
<span id="cb37-257"><a href="#cb37-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-258"><a href="#cb37-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-259"><a href="#cb37-259" aria-hidden="true" tabindex="-1"></a>About 48% of the sample are women and 52% are men.</span>
<span id="cb37-260"><a href="#cb37-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-261"><a href="#cb37-261" aria-hidden="true" tabindex="-1"></a><span class="fu">### A first scatter plot</span></span>
<span id="cb37-262"><a href="#cb37-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-263"><a href="#cb37-263" aria-hidden="true" tabindex="-1"></a>A natural starting question is: do workers with more education earn more?</span>
<span id="cb37-264"><a href="#cb37-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-265"><a href="#cb37-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-scatter}</span></span>
<span id="cb37-266"><a href="#cb37-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Wage versus years of education. Each dot is one of the 526 workers."</span></span>
<span id="cb37-267"><a href="#cb37-267" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage1<span class="sc">$</span>educ, wage1<span class="sc">$</span>wage,</span>
<span id="cb37-268"><a href="#cb37-268" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Years of education"</span>,</span>
<span id="cb37-269"><a href="#cb37-269" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Hourly wage (USD)"</span>,</span>
<span id="cb37-270"><a href="#cb37-270" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Wage vs. education"</span>,</span>
<span id="cb37-271"><a href="#cb37-271" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch  =</span> <span class="dv">16</span>,</span>
<span id="cb37-272"><a href="#cb37-272" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.3</span>))</span>
<span id="cb37-273"><a href="#cb37-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-274"><a href="#cb37-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-275"><a href="#cb37-275" aria-hidden="true" tabindex="-1"></a>The cloud of points slopes upward: on average, more educated workers earn higher wages. We can quantify the linear association with the **sample correlation**:</span>
<span id="cb37-276"><a href="#cb37-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-277"><a href="#cb37-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-corr}</span></span>
<span id="cb37-278"><a href="#cb37-278" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>educ)</span>
<span id="cb37-279"><a href="#cb37-279" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>exper)</span>
<span id="cb37-280"><a href="#cb37-280" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(wage1<span class="sc">$</span>educ, wage1<span class="sc">$</span>exper)</span>
<span id="cb37-281"><a href="#cb37-281" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-282"><a href="#cb37-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-283"><a href="#cb37-283" aria-hidden="true" tabindex="-1"></a>The correlation between wage and education is about $0.41$ --- a clearly positive but far-from-perfect linear association. Two further patterns stand out:</span>
<span id="cb37-284"><a href="#cb37-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-285"><a href="#cb37-285" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The correlation between wage and *experience* is positive but smaller than the correlation with education.</span>
<span id="cb37-286"><a href="#cb37-286" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The correlation between *education* and *experience* is **negative**. This is not because schooling destroys experience --- it reflects how individuals allocate time across the life cycle: more years in school mean fewer years in the workforce, mechanically. We will see in Chapter 3 that ignoring this kind of correlation among regressors can severely bias a simple regression of wage on education.</span>
<span id="cb37-287"><a href="#cb37-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-288"><a href="#cb37-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conditional means: a preview of regression</span></span>
<span id="cb37-289"><a href="#cb37-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-290"><a href="#cb37-290" aria-hidden="true" tabindex="-1"></a>A cleaner way to look at the data is to compute the **conditional mean** of wages given another variable. <span class="in">`tapply()`</span> does exactly that:</span>
<span id="cb37-291"><a href="#cb37-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-292"><a href="#cb37-292" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-cond-means}</span></span>
<span id="cb37-293"><a href="#cb37-293" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>female,  mean)</span>
<span id="cb37-294"><a href="#cb37-294" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>wage, wage1<span class="sc">$</span>married, mean)</span>
<span id="cb37-295"><a href="#cb37-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-296"><a href="#cb37-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-297"><a href="#cb37-297" aria-hidden="true" tabindex="-1"></a>Men earn about $7.10 per hour on average; women earn about $4.59. Married workers earn about $6.32 per hour; single workers about $5.16. These are **raw, unconditional** comparisons.</span>
<span id="cb37-298"><a href="#cb37-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-299"><a href="#cb37-299" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning}</span>
<span id="cb37-300"><a href="#cb37-300" aria-hidden="true" tabindex="-1"></a><span class="fu">## Common mistake: reading a conditional mean as a causal effect</span></span>
<span id="cb37-301"><a href="#cb37-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-302"><a href="#cb37-302" aria-hidden="true" tabindex="-1"></a>The 2.51-dollar gender gap and the 1.16-dollar marriage premium are **conditional means**, not causal effects. The men and women in this sample differ in occupation, sector, experience, hours worked, and many other characteristics; married and single workers differ in age and tenure. Without holding those confounders fixed, neither gap can be interpreted as the *ceteris paribus* effect of gender or marriage on wages. Holding confounders fixed is what multiple regression (Chapter 3) is for.</span>
<span id="cb37-303"><a href="#cb37-303" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-304"><a href="#cb37-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-305"><a href="#cb37-305" aria-hidden="true" tabindex="-1"></a>A more striking selection-bias illustration uses the conditional mean of *experience* given *education*:</span>
<span id="cb37-306"><a href="#cb37-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-307"><a href="#cb37-307" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ch01-sel-bias}</span></span>
<span id="cb37-308"><a href="#cb37-308" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(wage1<span class="sc">$</span>exper, wage1<span class="sc">$</span>educ, mean)</span>
<span id="cb37-309"><a href="#cb37-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-310"><a href="#cb37-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-311"><a href="#cb37-311" aria-hidden="true" tabindex="-1"></a>Workers with little schooling have *more* labour-market experience, and workers with a college degree have *less*. So when we compare wages across education levels, we are simultaneously comparing workers who differ in experience --- the comparison is confounded. This is the same kind of selection problem we saw in the ventilator and private-school examples, now in our actual dataset. We will fix it in Chapter 3 by including both <span class="in">`educ`</span> and <span class="in">`exper`</span> in a multiple regression.</span>
<span id="cb37-312"><a href="#cb37-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-313"><a href="#cb37-313" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb37-314"><a href="#cb37-314" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why `wage1` is a cross-section</span></span>
<span id="cb37-315"><a href="#cb37-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-316"><a href="#cb37-316" aria-hidden="true" tabindex="-1"></a><span class="in">`wage1`</span> records each worker **once**, all in 1976. There is no time index, no person identifier observed in several years. It is a clean cross-section. With this dataset alone we *cannot* track how a given worker's wage grows from one year to the next --- that would require a *panel*, e.g. the U.S. Panel Study of Income Dynamics (PSID) or the Spanish *Muestra Continua de Vidas Laborales* (MCVL). Knowing what your data *can* and *cannot* tell you is half of applied econometrics.</span>
<span id="cb37-317"><a href="#cb37-317" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-318"><a href="#cb37-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-319"><a href="#cb37-319" aria-hidden="true" tabindex="-1"></a><span class="fu">## Self-check {.unnumbered}</span></span>
<span id="cb37-320"><a href="#cb37-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-321"><a href="#cb37-321" aria-hidden="true" tabindex="-1"></a>Eight short multiple-choice questions. Try each one before opening the answer.</span>
<span id="cb37-322"><a href="#cb37-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-323"><a href="#cb37-323" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-324"><a href="#cb37-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q1. What is an econometric model?</span></span>
<span id="cb37-325"><a href="#cb37-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-326"><a href="#cb37-326" aria-hidden="true" tabindex="-1"></a>An econometric model differs from a purely economic (theoretical) model in that:</span>
<span id="cb37-327"><a href="#cb37-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-328"><a href="#cb37-328" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. It assumes the relationship between variables is exact and deterministic.</span>
<span id="cb37-329"><a href="#cb37-329" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. It adds a stochastic error term and a functional form so that unknown parameters can be estimated from data.</span>
<span id="cb37-330"><a href="#cb37-330" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. It does not require a sample of data because the parameters are derived from theory.</span>
<span id="cb37-331"><a href="#cb37-331" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. It is only used in macroeconomic problems, not in microeconomic ones.</span>
<span id="cb37-332"><a href="#cb37-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-333"><a href="#cb37-333" aria-hidden="true" tabindex="-1"></a>**Answer: B.** An econometric model couples a functional form with a random disturbance $u$, which makes the unknown parameters estimable from observed data.</span>
<span id="cb37-334"><a href="#cb37-334" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-335"><a href="#cb37-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-336"><a href="#cb37-336" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-337"><a href="#cb37-337" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q2. The role of the error term</span></span>
<span id="cb37-338"><a href="#cb37-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-339"><a href="#cb37-339" aria-hidden="true" tabindex="-1"></a>In the population regression model $y = \beta_0 + \beta_1 x + u$, the error term $u$:</span>
<span id="cb37-340"><a href="#cb37-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-341"><a href="#cb37-341" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Is the difference between $y_i$ and the OLS fitted value $\hat y_i$ in our sample.</span>
<span id="cb37-342"><a href="#cb37-342" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Is always equal to zero in the population.</span>
<span id="cb37-343"><a href="#cb37-343" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Captures every factor --- other than $x$ --- that influences $y$.</span>
<span id="cb37-344"><a href="#cb37-344" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Is observable as soon as we have data on $y$ and $x$.</span>
<span id="cb37-345"><a href="#cb37-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-346"><a href="#cb37-346" aria-hidden="true" tabindex="-1"></a>**Answer: C.** $u$ is a *population*, *unobservable* quantity collecting all omitted determinants of $y$. The residual $\hat u_i$ is its sample counterpart, computed only after estimation.</span>
<span id="cb37-347"><a href="#cb37-347" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-348"><a href="#cb37-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-349"><a href="#cb37-349" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-350"><a href="#cb37-350" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q3. Cross-section or not?</span></span>
<span id="cb37-351"><a href="#cb37-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-352"><a href="#cb37-352" aria-hidden="true" tabindex="-1"></a>A dataset with information on 526 workers interviewed in May 1976 (one observation per worker, all measured at the same time) is:</span>
<span id="cb37-353"><a href="#cb37-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-354"><a href="#cb37-354" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Cross-sectional data.</span>
<span id="cb37-355"><a href="#cb37-355" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Time-series data.</span>
<span id="cb37-356"><a href="#cb37-356" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Panel (longitudinal) data.</span>
<span id="cb37-357"><a href="#cb37-357" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Pooled cross-section data.</span>
<span id="cb37-358"><a href="#cb37-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-359"><a href="#cb37-359" aria-hidden="true" tabindex="-1"></a>**Answer: A.** Many units, one time period, no repeated observation of the same unit --- the textbook definition of a cross-section.</span>
<span id="cb37-360"><a href="#cb37-360" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-361"><a href="#cb37-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-362"><a href="#cb37-362" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-363"><a href="#cb37-363" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q4. Time series</span></span>
<span id="cb37-364"><a href="#cb37-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-365"><a href="#cb37-365" aria-hidden="true" tabindex="-1"></a>Annual Spanish unemployment rates from 1980 to 2024 are an example of:</span>
<span id="cb37-366"><a href="#cb37-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-367"><a href="#cb37-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Cross-sectional data.</span>
<span id="cb37-368"><a href="#cb37-368" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Time-series data.</span>
<span id="cb37-369"><a href="#cb37-369" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Panel data.</span>
<span id="cb37-370"><a href="#cb37-370" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Experimental data.</span>
<span id="cb37-371"><a href="#cb37-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-372"><a href="#cb37-372" aria-hidden="true" tabindex="-1"></a>**Answer: B.** One quantity (the unemployment rate) recorded at a regular frequency over time.</span>
<span id="cb37-373"><a href="#cb37-373" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-374"><a href="#cb37-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-375"><a href="#cb37-375" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-376"><a href="#cb37-376" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q5. Panel vs pooled cross-section</span></span>
<span id="cb37-377"><a href="#cb37-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-378"><a href="#cb37-378" aria-hidden="true" tabindex="-1"></a>A dataset follows 1{,}000 firms during the years 2010--2024, recording sales, employment and exports for each firm in every year. This is:</span>
<span id="cb37-379"><a href="#cb37-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-380"><a href="#cb37-380" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Cross-sectional data, since each firm-year is one row.</span>
<span id="cb37-381"><a href="#cb37-381" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. Pooled cross-section, since different units are sampled in each period.</span>
<span id="cb37-382"><a href="#cb37-382" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Time-series data, since it has a time dimension.</span>
<span id="cb37-383"><a href="#cb37-383" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Panel (longitudinal) data: the same units observed repeatedly over time.</span>
<span id="cb37-384"><a href="#cb37-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-385"><a href="#cb37-385" aria-hidden="true" tabindex="-1"></a>**Answer: D.** The same firms are tracked over multiple periods, which is exactly the panel structure.</span>
<span id="cb37-386"><a href="#cb37-386" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-387"><a href="#cb37-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-388"><a href="#cb37-388" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-389"><a href="#cb37-389" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q6. What does correlation tell us?</span></span>
<span id="cb37-390"><a href="#cb37-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-391"><a href="#cb37-391" aria-hidden="true" tabindex="-1"></a>A high positive correlation between two variables $X$ and $Y$ implies that:</span>
<span id="cb37-392"><a href="#cb37-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-393"><a href="#cb37-393" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. $X$ causes $Y$.</span>
<span id="cb37-394"><a href="#cb37-394" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. $Y$ causes $X$.</span>
<span id="cb37-395"><a href="#cb37-395" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. There exists a deterministic linear relationship between them.</span>
<span id="cb37-396"><a href="#cb37-396" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. They tend to move together, but this association may be driven by a third variable, by reverse causality, or by selection.</span>
<span id="cb37-397"><a href="#cb37-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-398"><a href="#cb37-398" aria-hidden="true" tabindex="-1"></a>**Answer: D.** Correlation is silent about causal direction or confounding. The ice-cream-and-drowning example in §1.4.2 is the canonical warning.</span>
<span id="cb37-399"><a href="#cb37-399" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-400"><a href="#cb37-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-401"><a href="#cb37-401" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-402"><a href="#cb37-402" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q7. Selection bias</span></span>
<span id="cb37-403"><a href="#cb37-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-404"><a href="#cb37-404" aria-hidden="true" tabindex="-1"></a>Selection bias arises when:</span>
<span id="cb37-405"><a href="#cb37-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-406"><a href="#cb37-406" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. The units that select into the treatment group differ systematically from those that do not, even before treatment.</span>
<span id="cb37-407"><a href="#cb37-407" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. The researcher chooses regressors based on $t$-statistics.</span>
<span id="cb37-408"><a href="#cb37-408" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. The sample size is too small to detect a true effect.</span>
<span id="cb37-409"><a href="#cb37-409" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. The dependent variable is measured with error.</span>
<span id="cb37-410"><a href="#cb37-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-411"><a href="#cb37-411" aria-hidden="true" tabindex="-1"></a>**Answer: A.** Selection bias is a property of the *assignment* of treatment, not of estimation or measurement. The ventilator example in §1.4.1 is the prototype.</span>
<span id="cb37-412"><a href="#cb37-412" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-413"><a href="#cb37-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-414"><a href="#cb37-414" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-415"><a href="#cb37-415" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q8. Randomisation as a remedy</span></span>
<span id="cb37-416"><a href="#cb37-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-417"><a href="#cb37-417" aria-hidden="true" tabindex="-1"></a>In which of the following research designs does randomisation *by construction* eliminate selection bias?</span>
<span id="cb37-418"><a href="#cb37-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-419"><a href="#cb37-419" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A. Comparing employed vs. unemployed individuals using cross-sectional survey data.</span>
<span id="cb37-420"><a href="#cb37-420" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>B. A randomised controlled trial (RCT) where the treatment is assigned by lottery.</span>
<span id="cb37-421"><a href="#cb37-421" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>C. Comparing students who chose to enrol in a private vs. a public school.</span>
<span id="cb37-422"><a href="#cb37-422" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>D. Comparing countries that adopted the euro vs. countries that did not.</span>
<span id="cb37-423"><a href="#cb37-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-424"><a href="#cb37-424" aria-hidden="true" tabindex="-1"></a>**Answer: B.** Only random assignment guarantees that, *on average*, treated and untreated units have the same pre-treatment characteristics.</span>
<span id="cb37-425"><a href="#cb37-425" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-426"><a href="#cb37-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-427"><a href="#cb37-427" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercises {.unnumbered}</span></span>
<span id="cb37-428"><a href="#cb37-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-429"><a href="#cb37-429" aria-hidden="true" tabindex="-1"></a>**Exercise 1.1 ★ --- Classifying datasets.** Classify each of the following datasets as cross-sectional, time-series, panel, or pooled cross-section.</span>
<span id="cb37-430"><a href="#cb37-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-431"><a href="#cb37-431" aria-hidden="true" tabindex="-1"></a>(a) Monthly Spanish CPI from 1980 to 2024.</span>
<span id="cb37-432"><a href="#cb37-432" aria-hidden="true" tabindex="-1"></a>(b) <span class="in">`wage1`</span>: 526 workers interviewed in May 1976, one row per worker.</span>
<span id="cb37-433"><a href="#cb37-433" aria-hidden="true" tabindex="-1"></a>(c) The Spanish EPA: each quarter, a fresh independent sample of households is drawn (no household is revisited); several quarters are then stacked.</span>
<span id="cb37-434"><a href="#cb37-434" aria-hidden="true" tabindex="-1"></a>(d) A dataset that follows the same 800 students from age 6 to age 18, recording their test scores every year.</span>
<span id="cb37-435"><a href="#cb37-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-436"><a href="#cb37-436" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-437"><a href="#cb37-437" aria-hidden="true" tabindex="-1"></a><span class="fu">## Show answer</span></span>
<span id="cb37-438"><a href="#cb37-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-439"><a href="#cb37-439" aria-hidden="true" tabindex="-1"></a>(a) Time-series. (b) Cross-sectional. (c) Pooled cross-section --- new units each period. (d) Panel: the *same* units are followed over multiple periods.</span>
<span id="cb37-440"><a href="#cb37-440" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-441"><a href="#cb37-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-442"><a href="#cb37-442" aria-hidden="true" tabindex="-1"></a>**Exercise 1.2 ★ --- Spotting selection bias.** For each scenario, state whether selection bias is a likely problem, and identify which characteristic drives the selection.</span>
<span id="cb37-443"><a href="#cb37-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-444"><a href="#cb37-444" aria-hidden="true" tabindex="-1"></a>(a) A hospital compares mortality of patients who received a ventilator with patients who did not.</span>
<span id="cb37-445"><a href="#cb37-445" aria-hidden="true" tabindex="-1"></a>(b) An economist compares the wages of workers who completed a job-training programme with the wages of workers who did not enrol.</span>
<span id="cb37-446"><a href="#cb37-446" aria-hidden="true" tabindex="-1"></a>(c) Researchers compare countries that adopted the euro in 1999 with countries that did not.</span>
<span id="cb37-447"><a href="#cb37-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-448"><a href="#cb37-448" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb37-449"><a href="#cb37-449" aria-hidden="true" tabindex="-1"></a><span class="fu">## Show answer</span></span>
<span id="cb37-450"><a href="#cb37-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-451"><a href="#cb37-451" aria-hidden="true" tabindex="-1"></a>(a) Yes --- severity of illness drives both ventilator assignment and mortality. (b) Yes --- self-selection into training is driven by motivation, prior earnings, and labour-market prospects, all of which also affect wages. (c) Yes --- countries that joined the euro were chosen on the basis of macroeconomic fundamentals (the Maastricht criteria), so they are not a random sample of European countries.</span>
<span id="cb37-452"><a href="#cb37-452" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb37-453"><a href="#cb37-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-454"><a href="#cb37-454" aria-hidden="true" tabindex="-1"></a>**Exercise 1.3 ★★ --- Sign of an omitted-variable bias.** Suppose you regress hourly wage on years of education in a sample of currently employed adults, *without* controlling for innate ability. Assume that (i) more able workers earn more, holding education fixed, and (ii) more able workers tend to acquire more education. Will the coefficient on <span class="in">`educ`</span> be biased upward (too positive) or downward (too negative)? Explain in one sentence.</span>
<span id="cb37-455"><a href="#cb37-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-456"><a href="#cb37-456" aria-hidden="true" tabindex="-1"></a>*A full answer is given in the Instructor Edition.*</span>
<span id="cb37-457"><a href="#cb37-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-458"><a href="#cb37-458" aria-hidden="true" tabindex="-1"></a>**Exercise 1.4 ★★ --- Designing a randomised experiment.** You want to know whether a free university preparation course (the treatment) causally raises the probability that high-school students from low-income families enrol in university. Sketch the design of a randomised experiment that would identify this causal effect. Be explicit about: the population, the assignment rule, the treatment and control groups, the outcome variable, and the time horizon. Briefly discuss one ethical objection your design will have to address.</span>
<span id="cb37-459"><a href="#cb37-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-460"><a href="#cb37-460" aria-hidden="true" tabindex="-1"></a>*A full answer is given in the Instructor Edition.*</span>
<span id="cb37-461"><a href="#cb37-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-462"><a href="#cb37-462" aria-hidden="true" tabindex="-1"></a>**Exercise 1.5 ★★ --- A naive omitted-variable model.** A worker's wage is generated by</span>
<span id="cb37-463"><a href="#cb37-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-464"><a href="#cb37-464" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-465"><a href="#cb37-465" aria-hidden="true" tabindex="-1"></a>w = 5 + 2 \cdot \mathit{edu} + u, \qquad \mathbb{E}<span class="co">[</span><span class="ot">u</span><span class="co">]</span> = 0,\ \operatorname{Var}(u) = 1,</span>
<span id="cb37-466"><a href="#cb37-466" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-467"><a href="#cb37-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-468"><a href="#cb37-468" aria-hidden="true" tabindex="-1"></a>where $\mathit{edu}\in<span class="sc">\{</span>0,1,2,3<span class="sc">\}</span>$ are years of post-compulsory education. Suppose that ability (collected in $u$) is correlated with education: $\mathbb{E}<span class="co">[</span><span class="ot">u\mid \mathit{edu}</span><span class="co">]</span> = 0.5\cdot \mathit{edu}$.</span>
<span id="cb37-469"><a href="#cb37-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-470"><a href="#cb37-470" aria-hidden="true" tabindex="-1"></a>(a) Compute $\mathbb{E}<span class="co">[</span><span class="ot">w\mid \mathit{edu}</span><span class="co">]</span>$.</span>
<span id="cb37-471"><a href="#cb37-471" aria-hidden="true" tabindex="-1"></a>(b) If we naively assume $\mathbb{E}<span class="co">[</span><span class="ot">u\mid \mathit{edu}</span><span class="co">]</span> = 0$ and read off the slope, what do we get? By how much do we *miss* the true marginal effect of an extra year of education?</span>
<span id="cb37-472"><a href="#cb37-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-473"><a href="#cb37-473" aria-hidden="true" tabindex="-1"></a>*A full answer is given in the Instructor Edition.*</span>
<span id="cb37-474"><a href="#cb37-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-475"><a href="#cb37-475" aria-hidden="true" tabindex="-1"></a>**Exercise 1.6 ★★★ --- Chocolate and Nobel prizes.** It has been documented <span class="co">[</span><span class="ot">@cgl2017</span><span class="co">]</span> that countries with higher per-capita chocolate consumption also win more Nobel prizes per capita. Is this evidence that chocolate consumption *causes* Nobel prizes? Identify (i) at least one plausible omitted variable, (ii) at least one alternative causal channel (reverse causation, selection of which countries get measured, etc.), and (iii) describe a *hypothetical* research design --- experimental or quasi-experimental --- that would allow you to learn the causal effect of chocolate on prize-winning. Be honest about why this design is unlikely to be feasible.</span>
<span id="cb37-476"><a href="#cb37-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-477"><a href="#cb37-477" aria-hidden="true" tabindex="-1"></a>*A full answer is given in the Instructor Edition.*</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>